# Main application settings.
app:
  APP_NAME:     "autobots"
  APP_VERSION:  "0.0.1"
# Logging settings.
log:
  DEF_LEVEL:     20
  MAX_SIZE:      5000000
  MAX_FILES:     5
# Event exeptions, i.e. events excluded from reporting.
report:
  EXECEPTIONS:
                - "REPORT"
                - "HARDWARE"
                - "CHECKLIST"
                - "XSIDLESTART"
